const horoscopes = [
  {
    id: '1',
    name: 'aquarius',
    dates: 'Jan 21 - Feb 19',
    symbol: 'Water Bearer',
    horoscope: 'Appreciate The Small Things',
  },
  {
    id: '2',
    name: 'aries',
    dates: 'Mar 21 - Apr 19',
    symbol: 'Ram',
    horoscope: 'Adjust to the new vibe',
  },
  {
    id: '3',
    name: 'cancer',
    dates: 'Jun 21 - Jul 22',
    symbol: 'Crab',
    horoscope: 'Sometimes people are actually shady',
  },
  {
    id: '4',
    name: 'capricorn',
    dates: 'Dec 22 - Feb 19',
    symbol: 'Goat',
    horoscope: 'you have value',
  },
  {
    id: '5',
    name: 'gemini',
    dates: 'May 21 - Jun 20',
    symbol: 'Twins',
    horoscope: 'you have to choose',
  },
  {
    id: '6',
    name: 'leo',
    dates: 'Jul 23 - Aug 22',
    symbol: 'Lion',
    horoscope: 'quiet your mental spirals',
  },
  {
    id: '7',
    name: 'libra',
    dates: 'Sept 23 - Oct 22',
    symbol: 'Balance',
    horoscope: 'you need to decide',
  },
  {
    id: '8',
    name: 'pisces',
    dates: 'Feb 19 - Mar 20',
    symbol: 'Fish',
    horoscope: 'success can be personal not global',
  },
  {
    id: '9',
    name: 'sagittarius',
    dates: 'Nov 22 - Dec 21',
    symbol: 'Archer',
    horoscope: 'you are a whole not the sum of broken parts',
  },
  {
    id: '10',
    name: 'scorpio',
    dates: 'Oct 23 - Nov 21',
    symbol: 'Scorpion',
    horoscope: 'take time to rest',
  },
  {
    id: '11',
    name: 'taurus',
    dates: 'Apr 20 - May 20',
    symbol: 'Bull',
    horoscope: 'roadblocks happen',
  },
  {
    id: '12',
    name: 'virgo',
    dates: 'Aug 23 - Sep 22',
    symbol: 'Virgin',
    horoscope: 'focus',
  },
];

module.exports = { horoscopes };
